"""Pure, explicit-module tests; every transcript/time below is a SYNTHETIC fixture.

No fixture is claimed to be an ASR result or an acoustic/performance measurement.
Use unittest's explicit tests.test_production_modes module, not suite discovery.
Importing the application/config, dotenv, media providers or real data is forbidden.
"""

from __future__ import annotations

import ast
import builtins
import importlib
import importlib.util
import io
import json
import math
import socket
import sys
import time
import unittest
from copy import deepcopy
from pathlib import Path
from typing import Any
from unittest.mock import patch

from pydantic import ValidationError

from backend import production_modes as pm
from backend.production_modes import (
    MATCH_LOW,
    MATCH_OK,
    MODE_RULES,
    PACING_CPM,
    STAGE_WEIGHTS,
    JumpCut,
    QuoteTake,
    SentenceInput,
    SourceHint,
    Speaker,
    TranscriptSegment,
    Word,
    align_quotes,
    calculate_jumpcuts,
    evaluate_mode_checks,
    normalize_text,
    parse_sentences,
    quote_text_is_contiguous,
    refine_cut,
    validate_quote_trim,
)


def segment(text: str, *, id: str = "seg", start: float = 0.0, end: float = 6.0,
            speaker: str = "S1", words: list[dict] | None = None,
            snr: float | None = None) -> dict:
    return {"id": id, "start": start, "end": end, "speaker_id": speaker,
            "text": text, "words": words or [], "snr_db": snr}


def upload(*segments: dict, id: str = "u1", seconds: float = 100.0) -> dict:
    return {"id": id, "sec": seconds, "name": "synthetic fixture", "transcript": list(segments)}


def quote(text: str, **kwargs) -> SentenceInput:
    return SentenceInput(idx=kwargs.pop("idx", 0), text=text, kind="quote", **kwargs)


def take() -> QuoteTake:
    # Deliberately uneven supplied timings, not generated by dividing duration.
    return QuoteTake(
        take_id="fixture", upload_id="upload", start=0.8, end=6.5,
        speaker_id="S1", asr_text="我们，今天欢迎大家。", score=1.0,
        snr_db=22.0,
        words=[Word(w="我们", s=1.0, e=1.4), Word(w="今天", s=1.6, e=3.1),
               Word(w="欢迎", s=3.2, e=3.7), Word(w="大家", s=3.8, e=6.2)],
    )


def row(idx: int, file: str = "u1", start: float = 0.0, end: float = 2.0,
        **kwargs) -> dict:
    result = {"idx": idx, "kind": "quote", "text": "今天开放", "source": {
        "upload_id": file, "start": start, "end": end, "speaker_id": "S1",
        "score": 1.0, "asr_text": "今天开放", "snr_db": None,
    }}
    result.update(kwargs)
    return result


def reference_distance(a: str, b: str) -> int:
    """Edit-distance oracle ONLY for _distance/text-difference, not §10.3."""
    grid = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]
    for i in range(len(a) + 1):
        grid[i][0] = i
    for j in range(len(b) + 1):
        grid[0][j] = j
    for i in range(1, len(a) + 1):
        for j in range(1, len(b) + 1):
            grid[i][j] = min(grid[i - 1][j] + 1, grid[i][j - 1] + 1,
                             grid[i - 1][j - 1] + (a[i - 1] != b[j - 1]))
    return grid[-1][-1]


def reference_similarity(a: str, b: str) -> float:
    """Independent §10.3 on normalized strings; list removal, not Counter/code reuse."""
    if not a or not b:
        return 0.0
    if min(len(a), len(b)) == 1:
        return float(a in b or b in a)
    remaining = [b[i:i + 2] for i in range(len(b) - 1)]
    intersection = 0
    for i in range(len(a) - 1):
        gram = a[i:i + 2]
        if gram in remaining:
            remaining.remove(gram)
            intersection += 1
    return max(2 * intersection / (len(a) + len(b) - 2),
               intersection / min(len(a) - 1, len(b) - 1))


def reference_best(query: str, text: str, boundaries: tuple[int, ...] | None = None) -> float:
    """Exhaust every legal endpoint pair, retaining full precision."""
    points = boundaries if boundaries is not None else tuple(range(len(text) + 1))
    return max((reference_similarity(query, text[a:b])
                for a in points for b in points if b > a), default=0.0)


def assert_original_blocked(test: unittest.TestCase, requested: str, result: dict[str, Any]) -> None:
    """Raw lexical success cannot authorize C or fabricate contiguous evidence."""
    test.assertIsNotNone(result["source"])
    test.assertFalse(quote_text_is_contiguous(requested, result["source"]))
    for gate in ("warn", "block"):
        issues = evaluate_mode_checks([{**result, "text": requested}], [], "original", {}, gate)
        issue = next(v for v in issues if v["code"] == "QUOTE_NONCONTIGUOUS")
        test.assertEqual((issue["level"], issue["severity"]), (0, "error"))


class ModelsAndRulesTests(unittest.TestCase):
    def test_fixed_constants_and_normalized_ten_stage_weights(self):
        self.assertEqual(PACING_CPM, {"slow": 230, "normal": 265, "fast": 290})
        self.assertEqual((MATCH_LOW, MATCH_OK), (0.6, 0.85))
        self.assertEqual(set(STAGE_WEIGHTS), {"voiceover", "mixed", "original"})
        for mode, weights in STAGE_WEIGHTS.items():
            with self.subTest(mode=mode):
                self.assertEqual(len(weights), 10)
                self.assertAlmostEqual(sum(weights), 1.0)
                self.assertTrue(all(math.isfinite(w) and w > 0 for w in weights))
                stages = MODE_RULES["modes"][mode]["stages"]
                self.assertEqual([s["n"] for s in stages], list(range(1, 11)))
                self.assertTrue(all(s["name"] and s["description"] for s in stages))
        self.assertEqual(STAGE_WEIGHTS["original"][1] / STAGE_WEIGHTS["original"][3], 6)

    def test_json_is_the_shared_rule_source(self):
        raw = json.loads(Path(pm.__file__).with_name("mode_rules.json").read_text(encoding="utf-8"))
        self.assertEqual(raw, MODE_RULES)
        self.assertEqual(raw["rules_version"], 2)
        self.assertEqual(raw["limits"]["quote_snr_min_db"], 18)
        self.assertEqual(raw["limits"]["alternative_takes"], 5)
        self.assertEqual(raw["limits"]["alternative_match_min"], 0.5)
        self.assertEqual(raw["limits"]["lower_third_repeat_gap_seconds"], 60)
        self.assertNotIn("grade", raw)
        self.assertNotIn("eta", raw)

    def test_models_reject_grade_and_other_unknown_fields(self):
        fixtures = [SourceHint(upload_id="u", seg_id="s"), quote("原话"),
                    Word(w="词", s=0, e=1), TranscriptSegment(**segment("原话")),
                    Speaker(id="S1"), take(), JumpCut(after_row=0, cover="zoom")]
        for model in fixtures:
            with self.subTest(model=type(model).__name__):
                with self.assertRaises(ValidationError):
                    type(model).model_validate({**model.model_dump(), "grade": "primary"})
                self.assertNotIn("grade", model.model_dump())

    def test_sentence_validation(self):
        for patch_value in ({"idx": -1}, {"idx": True}, {"idx": 0.5},
                            {"text": ""}, {"text": " \n"}, {"text": "字" * 2001},
                            {"kind": "grade"}, {"source_hint": {"upload_id": "u", "seg_id": " "}}):
            with self.subTest(patch_value=list(patch_value)):
                with self.assertRaises(ValidationError):
                    SentenceInput.model_validate({"idx": 0, "text": "句子", "kind": "quote", **patch_value})
        self.assertEqual(len(quote("字" * 2000).text), 2000)

    def test_finite_ordered_word_times(self):
        for change in ({"s": -1}, {"e": 0}, {"s": 2, "e": 1}, {"s": 1, "e": 1},
                       {"s": float("nan")}, {"e": float("inf")}, {"e": -float("inf")},
                       {"s": True}, {"e": "1"}, {"w": " "}):
            with self.subTest(change=change):
                with self.assertRaises(ValidationError):
                    Word.model_validate({"w": "词", "s": 0, "e": 1, **change})

    def test_other_numeric_model_boundaries(self):
        for change in ({"start": -1}, {"start": float("nan")}, {"end": float("inf")},
                       {"end": 0}, {"confidence": 1.01}, {"snr_db": float("nan")}):
            with self.subTest(change=change):
                with self.assertRaises(ValidationError):
                    TranscriptSegment.model_validate({**segment("内容"), **change})
        for change in ({"score": float("nan")}, {"score": 1.1}, {"start": True},
                       {"snr_db": float("inf")}, {"end": 0.8}):
            with self.subTest(change=change):
                with self.assertRaises(ValidationError):
                    QuoteTake.model_validate({**take().model_dump(), **change})
        with self.assertRaises(ValidationError):
            Speaker(id="s", seconds=float("inf"))
        with self.assertRaises(ValidationError):
            Speaker(id="s", appearances=-1)

    def test_segment_without_words_is_explicitly_not_word_precision(self):
        source = QuoteTake(take_id="a", upload_id="u", start=0, end=2,
                           speaker_id="s", asr_text="真实整段", score=1.0, words=[])
        self.assertEqual(source.precision, "segment")
        self.assertEqual(source.words, [])

    def test_word_evidence_cannot_erase_number_signs_or_decimal_points(self):
        for text, word in (("负三度", "三度"), ("-3度", "3度"), ("3.5元", "35元")):
            with self.subTest(text=text, word=word):
                source = QuoteTake(take_id="a", upload_id="u", start=0, end=2,
                                   speaker_id="s", asr_text=text, score=1.0,
                                   words=[Word(w=word, s=0, e=2)])
                self.assertEqual(source.precision, "segment")


class ParsingTests(unittest.TestCase):
    def test_title_is_first_nonempty_line_and_indices_are_zero_based(self):
        sentences = parse_sentences("\ufeff\r\n \r\n标题！\r\n\r\n正文，第二句。", "voiceover")
        self.assertEqual([(s.idx, s.text, s.kind) for s in sentences],
                         [(0, "正文", "narration"), (1, "第二句", "narration")])

    def test_voiceover_punctuation_and_enumeration(self):
        result = parse_sentences("标题\n苹果、梨,很好；开门;你好!结束?下一句.最后。", "voiceover")
        self.assertEqual([s.text for s in result], ["苹果、梨", "很好", "开门", "你好", "结束", "下一句", "最后"])
        self.assertTrue(all(s.kind == "narration" for s in result))

    def test_decimal_and_quoted_event_names_are_not_split(self):
        result = parse_sentences("标题\n票价3.14元，活动叫“高新，年味”。", "voiceover")
        self.assertEqual([s.text for s in result], ["票价3.14元", "活动叫“高新，年味”"])

    def test_all_required_mixed_markers_and_speaker_metadata(self):
        script = "标题\n旁白：先说背景，活动开幕。\n同期：今天很热闹，欢迎大家。\n【同期】我们来了！\n同期 王红（主办方）：大家好。谢谢！\n李大姐（摊主）：是自己做的，用本地猪肉。"
        result = parse_sentences(script, "mixed")
        self.assertEqual([s.kind for s in result], ["narration", "narration", "quote", "quote", "quote", "quote", "quote"])
        self.assertEqual(result[2].text, "今天很热闹，欢迎大家")
        self.assertEqual(result[4].speaker_hint, "王红（主办方）")
        self.assertEqual(result[5].speaker_hint, "王红（主办方）")
        self.assertEqual(result[6].speaker_hint, "李大姐（摊主）")

    def test_mixed_not_every_colon_is_a_speaker(self):
        result = parse_sentences("标题\n活动时间：上午九点。\n同期增长很快。", "mixed")
        self.assertEqual([s.kind for s in result], ["narration", "narration"])

    def test_original_line_and_terminal_breaks_preserve_commas(self):
        result = parse_sentences("标题\n买了腊肉，还有礼盒\n自己做的，用本地猪肉。欢迎！", "original")
        self.assertEqual([s.text for s in result], ["买了腊肉，还有礼盒", "自己做的，用本地猪肉", "欢迎"])
        self.assertTrue(all(s.kind == "quote" for s in result))

    def test_manual_mixed_overrides_take_priority_without_reparsing(self):
        result = parse_sentences("标题\n同期：长句，仍是同句。\n一段旁白。", "mixed", {0: "narration", 1: "quote"})
        self.assertEqual([(s.text, s.kind) for s in result], [("长句，仍是同句", "narration"), ("一段旁白", "quote")])

    def test_invalid_overrides_and_modes_fail(self):
        for mode, overrides in (("voiceover", {0: "quote"}), ("original", {0: "narration"}),
                                ("mixed", {3: "quote"}), ("mixed", {True: "quote"}),
                                ("mixed", {0: "grade"}), ("invalid", None)):
            with self.subTest(mode=mode, overrides=overrides):
                with self.assertRaises(ValueError):
                    parse_sentences("标题\n内容", mode, overrides)

    def test_empty_and_title_only(self):
        for script in ("", "\n \n", "只有标题", "\n只有标题\n\n"):
            self.assertEqual(parse_sentences(script, "mixed"), [])


class NormalizationTests(unittest.TestCase):
    def test_nfkc_casefold_whitespace_and_punctuation(self):
        self.assertEqual(normalize_text(" ＡＢＣ，‘采访’！？\n"), "abc采访")
        self.assertEqual(normalize_text("Café"), normalize_text("Cafe\u0301"))
        self.assertEqual(normalize_text("\u1100\u1161"), normalize_text("가"))

    def test_dates_days_and_address_numbers(self):
        self.assertEqual(normalize_text("一月三十一号"), "1月31日")
        self.assertEqual(normalize_text("１月３１日"), "1月31日")
        self.assertEqual(normalize_text("二〇二六年九月二十八日"), "2026年9月28日")
        self.assertEqual(normalize_text("鲁班路九十五号"), "鲁班路95号")
        self.assertNotEqual(normalize_text("95号"), normalize_text("95日"))

    def test_chinese_numbers_units_and_financial_forms(self):
        cases = {"两百": "200", "兩百": "200", "一千零二十": "1020", "十": "10",
                 "十一": "11", "二十三": "23", "一万零三": "10003", "二亿三千万": "230000000",
                 "壹佰贰拾叁": "123", "貳佰參拾肆": "234", "伍佰陆拾柒": "567",
                 "捌仟玖佰": "8900", "三点五": "3.5", "负三点五": "-3.5"}
        for text, expected in cases.items():
            with self.subTest(text=text):
                self.assertEqual(normalize_text(text), expected)

    def test_numeric_sign_and_decimal_do_not_destroy_meaning(self):
        self.assertNotEqual(normalize_text("3.5元"), normalize_text("35元"))
        self.assertNotEqual(normalize_text("负三度"), normalize_text("三度"))

    def test_discourse_fillers_removed_without_substring_damage(self):
        self.assertEqual(normalize_text("嗯，啊，呃，那个，就是说，就是，然后我们欢迎大家"), "我们欢迎大家")
        self.assertEqual(normalize_text("嗯…就是希望大家来。"), "希望大家来")
        for text in ("那个人", "然后果很严重", "呃逆", "阿姨", "就是事实", "我们一直在一起", "千万别忘记"):
            with self.subTest(text=text):
                self.assertEqual(normalize_text(text), text)

    def test_mapping_covers_entire_multiword_number(self):
        text = "嗯，一月三十一号欢迎"
        value = pm._normalize_with_mapping(text)
        self.assertEqual(value.text, "1月31日欢迎")
        self.assertEqual(len(value.text), len(value.spans))
        left = value.text.index("3")
        self.assertEqual(text[slice(*value.spans[left])], "三十一")
        self.assertEqual(value.spans[left], value.spans[left + 1])

    def test_whitespace_inside_spoken_numbers_does_not_change_value(self):
        self.assertEqual(normalize_text("一 月 三 十 一 号"), "1月31日")
        self.assertEqual(normalize_text("两\n百零\t三"), "203")
        self.assertEqual(normalize_text("－ ３．５"), "-3.5")


class AlignmentTests(unittest.TestCase):
    def test_exact_numeric_transcript_is_one_not_artificial_point_nine(self):
        sentence = quote("我们这个市集会一直持续到1月31日，欢迎大家来")
        text = "我们这个市集会一直持续到一月三十一号，欢迎大家来"
        result = align_quotes([sentence], [upload(segment(text, start=3, end=9))])[0]
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["source"]["precision"], "segment")
        self.assertEqual(result["asr_text"], text)
        self.assertEqual(result["source"]["words"], [])

    def test_cross_segment_same_speaker_with_supplied_word_boundaries(self):
        first = segment("我们今天", id="a", start=1, end=3.0, words=[
            {"w": "我们", "s": 1.12, "e": 1.61}, {"w": "今天", "s": 1.81, "e": 2.77}])
        second = segment("欢迎大家", id="b", start=3.0, end=6.0, words=[
            {"w": "欢迎", "s": 3.03, "e": 3.7}, {"w": "大家", "s": 4.1, "e": 5.71}])
        result = align_quotes([quote("我们今天欢迎大家")], [upload(first, second)])[0]
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["source"]["precision"], "word")
        self.assertEqual(result["source"]["segment_ids"], ["a", "b"])
        self.assertEqual(result["asr_text"], "我们今天\n欢迎大家")
        self.assertEqual(result["source"]["words"], first["words"] + second["words"])
        self.assertAlmostEqual(result["start"], 1.0)
        self.assertAlmostEqual(result["end"], 5.91)

    def test_cross_segment_without_words_uses_entire_segments_and_preserves_text(self):
        result = align_quotes([quote("今天欢迎大家")], [upload(
            segment("前文今天", id="a", start=1, end=3),
            segment("欢迎大家后文", id="b", start=3.1, end=7),
        )])[0]
        self.assertEqual(result["score"], 1.0)
        self.assertEqual((result["start"], result["end"]), (1, 7))
        self.assertEqual(result["asr_text"], "前文今天\n欢迎大家后文")
        self.assertEqual(result["source"]["matched_text"], "今天\n欢迎大家")
        with self.assertRaises(ValueError):
            validate_quote_trim(QuoteTake(**result["source"]), 2, 7)

    def test_cannot_construct_sentence_across_speakers_or_large_silence(self):
        for second in (segment("戊己庚辛", id="b", start=2, end=4, speaker="S2"),
                       segment("戊己庚辛", id="b", start=10, end=12)):
            with self.subTest(second=second["start"]):
                result = align_quotes([quote("甲乙丙丁戊己庚辛")], [upload(segment("甲乙丙丁", end=2), second)])[0]
                self.assertEqual(result["score"], 1.0)
                self.assertEqual(result["source"]["segment_ids"], ["seg"])
                self.assertEqual((result["asr_text"], result["start"], result["end"]), ("甲乙丙丁", 0, 2))
                self.assertEqual(result["source"]["words"], [])
                assert_original_blocked(self, "甲乙丙丁戊己庚辛", result)

    def test_overlap_or_reversed_asr_segments_are_not_joined(self):
        result = align_quotes([quote("甲乙丙丁戊己庚辛")], [upload(
            segment("甲乙丙丁", id="a", start=0, end=3),
            segment("戊己庚辛", id="b", start=2, end=4),
        )])[0]
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["source"]["segment_ids"], ["a"])
        self.assertEqual((result["asr_text"], result["start"], result["end"]), ("甲乙丙丁", 0, 3))
        self.assertEqual(result["source"]["words"], [])
        assert_original_blocked(self, "甲乙丙丁戊己庚辛", result)

    def test_typo_uses_spec_containment_not_confidence_or_truth(self):
        text = "今天市集正式开放欢迎大冢前来参观"
        target = "今天市集正式开放欢迎大家前来参观"
        result = align_quotes([quote(target)], [upload(segment(text))])[0]
        expected = reference_best(normalize_text(target), normalize_text(text))
        self.assertEqual(result["score"], expected)
        self.assertEqual(expected, 1.0)
        self.assertEqual(result["asr_text"], text)
        self.assertNotIn("大家", result["asr_text"])
        assert_original_blocked(self, target, result)

    def test_missing_word_is_not_invented(self):
        target = "今天市集正式开放欢迎大家前来参观"
        text = "今天市集开放欢迎大家前来参观"
        result = align_quotes([quote(target)], [upload(segment(text))])[0]
        self.assertEqual(result["score"], reference_best(normalize_text(target), normalize_text(text)))
        self.assertEqual(result["asr_text"], text)
        self.assertNotIn("正式", result["asr_text"])
        assert_original_blocked(self, target, result)

    def test_shared_character_score_is_not_quote_truth(self):
        result = align_quotes([quote("甲乙丙丁戊")], [upload(segment("甲壬癸子丑"))])[0]
        self.assertEqual(result["score"], reference_best("甲乙丙丁戊", "甲壬癸子丑"))
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["source"]["matched_text"], "甲")
        self.assertEqual(result["asr_text"], "甲壬癸子丑")
        self.assertEqual(result["alt_takes"], [])
        assert_original_blocked(self, "甲乙丙丁戊", result)

    def test_known_missing_demo_quote_remains_blocked_despite_high_score(self):
        sources = [upload(segment("我们这个市集会一直持续到一月三十一号，欢迎大家来")),
                   upload(segment("我们家的腊肠是自己熏的，用的是广西本地的猪肉"), id="u2")]
        result = align_quotes([quote("今年我们还请了舞狮队")], sources)[0]
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["source"]["matched_text"], "我们")
        self.assertEqual(result["asr_text"], sources[0]["transcript"][0]["text"])
        self.assertEqual(result["source"]["words"], [])
        assert_original_blocked(self, "今年我们还请了舞狮队", result)
        for alternative in result["alt_takes"]:
            self.assertFalse(quote_text_is_contiguous("今年我们还请了舞狮队", alternative))

    def test_repeated_multiple_speakers_rank_hint_before_snr(self):
        sources = [upload(segment("欢迎大家前来参观", speaker="S1", snr=30)),
                   upload(segment("欢迎大家前来参观", speaker="S2", snr=16), id="u2")]
        people = [Speaker(id="S1", name="王红", title="主办方"), Speaker(id="S2", name="李姐", title="摊主")]
        result = align_quotes([quote("欢迎大家前来参观", speaker_hint="李姐（摊主）")], sources, people)[0]
        self.assertEqual(result["speaker_id"], "S2")
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["alt_takes"], [])

    def test_speaker_hint_can_rank_high_score_but_cannot_authorize_unrelated_quote(self):
        sources = [upload(segment("甲壬癸子丑", speaker="S1")),
                   upload(segment("甲乙丙丁戊", speaker="S2"), id="u2")]
        result = align_quotes([quote("甲乙丙丁戊", speaker_hint="S1")], sources)[0]
        self.assertEqual(result["speaker_id"], "S1")
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["asr_text"], "甲壬癸子丑")
        self.assertEqual(result["alt_takes"], [])
        assert_original_blocked(self, "甲乙丙丁戊", result)

    def test_explicit_speaker_precedes_conflicting_source_hint_without_score_boost(self):
        near = segment("今天市集正式开放欢迎大冢前来参观", id="near", start=10, end=15, snr=16)
        outside = segment("今天市集正式开放欢迎大家前来参观", id="far", start=40, end=45, speaker="S2", snr=35)
        result = align_quotes([quote("今天市集正式开放欢迎大家前来参观", speaker_hint="S2",
                              source_hint=SourceHint(upload_id="u1", seg_id="near"))], [upload(near, outside)])[0]
        self.assertEqual(result["start"], 40)
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["source"]["score"], result["score"])
        self.assertEqual(result["alt_takes"], [])

    def test_source_hint_searches_plus_minus_five_seconds_and_falls_back(self):
        sources = [upload(segment("无关介绍", id="hint", start=10, end=11),
                          segment("欢迎大家前来参观", id="near", start=14, end=18),
                          segment("欢迎大家前来参观", id="far", start=40, end=44, snr=30))]
        hinted = quote("欢迎大家前来参观", source_hint=SourceHint(upload_id="u1", seg_id="hint"))
        self.assertEqual(align_quotes([hinted], sources)[0]["start"], 14)
        stale = quote("欢迎大家前来参观", source_hint=SourceHint(upload_id="missing", seg_id="missing"))
        self.assertEqual(align_quotes([stale], sources)[0]["start"], 40)

    def test_snr_then_complete_timing_and_internal_pauses_break_equal_scores(self):
        sources = [upload(segment("欢迎大家", start=0, end=2, snr=None)),
                   upload(segment("欢迎大家", start=0, end=2, snr=15), id="u2"),
                   upload(segment("欢迎大家", start=0, end=3, snr=25), id="u3")]
        result = align_quotes([quote("欢迎大家")], sources)[0]
        self.assertEqual(result["upload_id"], "u3")
        self.assertIsNone(result["alt_takes"][-1]["snr_db"])
        first = upload(segment("欢迎大家", words=[{"w": "欢迎", "s": 0.2, "e": 1.1}, {"w": "大家", "s": 3.5, "e": 4.8}], snr=20), id="a")
        second = upload(segment("欢迎大家", words=[{"w": "欢迎", "s": 0.2, "e": 1.1}, {"w": "大家", "s": 1.3, "e": 2.4}], snr=20), id="z")
        self.assertEqual(align_quotes([quote("欢迎大家")], [first, second])[0]["upload_id"], "z")

    def test_repeated_occurrences_provide_at_most_five_distinct_alternatives(self):
        sources = [upload(*(segment("欢迎大家前来参观", id=str(i), start=i * 10, end=i * 10 + 3, snr=20) for i in range(6)))]
        result = align_quotes([quote("欢迎大家前来参观")], sources)[0]
        self.assertEqual(len(result["alt_takes"]), 5)
        self.assertEqual(len({t["take_id"] for t in [result["source"], *result["alt_takes"]]}), 6)
        self.assertTrue(all(t["start"] > result["start"] for t in result["alt_takes"]))
        # Keep the original six occurrences above; add a seventh separately
        # to prove the cap, not merely that five alternatives can exist.
        expanded = deepcopy(sources)
        expanded[0]["transcript"].append(segment("欢迎大家前来参观", id="6", start=60, end=63, snr=20))
        capped = align_quotes([quote("欢迎大家前来参观")], expanded)[0]
        self.assertEqual(capped, result)

    def test_stable_take_id_ignores_paths_filenames_order_and_sentence_id(self):
        a = upload(segment("欢迎大家", start=1, end=3), id="a")
        b = upload(segment("欢迎大家", start=1, end=3), id="b")
        a["path"] = "C:/private/source.mov"
        first = align_quotes([quote("欢迎大家")], [a, b])[0]
        a["path"], a["name"] = "/different/private/location", "different.mp4"
        second = align_quotes([quote("欢迎大家", idx=71)], [b, a])[0]
        self.assertEqual(first["source"]["take_id"], second["source"]["take_id"])
        serialized = json.dumps(second)
        self.assertNotIn("private", serialized)
        self.assertNotIn("different", serialized)

    def test_untrusted_word_coverage_or_times_degrade_without_interpolation(self):
        fixtures = [
            [{"w": "今天", "s": 0.1, "e": 1}],
            [{"w": "今天", "s": 0.1, "e": 1.2}, {"w": "欢迎", "s": 1.1, "e": 2}],
            [{"w": "今天", "s": 1.5, "e": 2}, {"w": "欢迎", "s": 0.1, "e": 1.2}],
            [{"w": "今天", "s": 0.1, "e": 1}, {"w": "欢迎", "s": 2, "e": 7}],
            [{"w": "今田", "s": 0.1, "e": 1}, {"w": "欢迎", "s": 2, "e": 3}],
        ]
        for words in fixtures:
            with self.subTest(words=words):
                result = align_quotes([quote("今天欢迎")], [upload(segment("今天欢迎", words=words))])[0]
                self.assertEqual(result["source"]["precision"], "segment")
                self.assertEqual(result["source"]["words"], [])
                self.assertEqual((result["start"], result["end"]), (0, 6))

    def test_word_tokens_remain_indivisible_and_uneven(self):
        cues = [{"w": "前话", "s": 0.1, "e": 0.6}, {"w": "采访内容", "s": 1.0, "e": 5.0},
                {"w": "尾声", "s": 5.5, "e": 5.8}]
        result = align_quotes([quote("采访内容")], [upload(segment("前话采访内容尾声", words=cues))])[0]
        self.assertEqual(result["source"]["words"], [cues[1]])
        self.assertEqual((result["start"], result["end"]), (0.88, 5.2))
        # Containment may score 1, but cannot acquire fabricated half-word timing.
        inside = align_quotes([quote("内容")], [upload(segment("前话采访内容尾声", words=cues))])[0]
        self.assertEqual(inside["score"], reference_similarity("内容", "采访内容"))
        self.assertEqual(inside["source"]["words"], [cues[1]])
        self.assertEqual(inside["asr_text"], "采访内容")
        self.assertEqual((inside["start"], inside["end"]), (0.88, 5.2))
        with self.assertRaises(ValueError):
            validate_quote_trim(QuoteTake(**inside["source"]), 3.0, 5.2)

    def test_date_number_mapping_does_not_drop_first_or_last_number_word(self):
        cues = [{"w": "嗯", "s": 0.1, "e": 0.3}, {"w": "一月", "s": 0.8, "e": 1.3},
                {"w": "三十", "s": 1.4, "e": 2.7}, {"w": "一号", "s": 2.8, "e": 3.1},
                {"w": "欢迎", "s": 4, "e": 4.9}]
        result = align_quotes([quote("1月31日")], [upload(segment("嗯，一月三十一号欢迎", words=cues))])[0]
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["asr_text"], "一月三十一号")
        self.assertEqual(result["source"]["words"], cues[1:4])
        self.assertAlmostEqual(result["start"], 0.68)
        self.assertAlmostEqual(result["end"], 3.3)

    def test_one_row_per_input_and_client_kinds_are_authoritative(self):
        sentences = [SentenceInput(idx=90, kind="narration", text="同期：欢迎大家"), quote("欢迎大家", idx=3)]
        before = [s.model_dump() for s in sentences]
        sources = [upload(segment("欢迎大家"))]
        original_sources = deepcopy(sources)
        result = align_quotes(sentences, sources)
        self.assertEqual([(r["idx"], r["kind"]) for r in result], [(90, "narration"), (3, "quote")])
        self.assertIsNone(result[0]["source"])
        self.assertIsNotNone(result[1]["source"])
        self.assertEqual(before, [s.model_dump() for s in sentences])
        self.assertEqual(sources, original_sources)

    def test_empty_transcript_and_filler_only_sentence_never_succeed(self):
        self.assertIsNone(align_quotes([quote("内容")], [upload()])[0]["source"])
        self.assertIsNone(align_quotes([quote("嗯，啊")], [upload(segment("嗯，啊"))])[0]["source"])

    def test_nested_transcript_segments_input(self):
        item = upload(segment("欢迎大家"))
        item["transcript"] = {"segments": item["transcript"]}
        self.assertEqual(align_quotes([quote("欢迎大家")], [item])[0]["score"], 1)

    def test_chinese_number_split_across_transcript_segments(self):
        sources = [upload(segment("一月三十", id="a", start=1, end=3),
                          segment("一号欢迎", id="b", start=3.1, end=5))]
        result = align_quotes([quote("1月31日欢迎")], sources)[0]
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["asr_text"], "一月三十\n一号欢迎")

    def test_handles_may_extend_past_asr_segment_but_not_the_source(self):
        item = upload(segment("欢迎大家", start=1, end=3, words=[
            {"w": "欢迎", "s": 1, "e": 1.6}, {"w": "大家", "s": 1.7, "e": 3}]), seconds=5)
        result = align_quotes([quote("欢迎大家")], [item])[0]
        self.assertEqual((result["start"], result["end"]), (0.88, 3.2))

    def test_handles_do_not_admit_other_speakers_or_untimed_neighbour_segments(self):
        selected = segment("欢迎大家", id="selected", start=1, end=3, words=[
            {"w": "欢迎", "s": 1, "e": 1.6}, {"w": "大家", "s": 1.7, "e": 3}])
        item = upload(segment("前文", id="before", start=0, end=0.95, speaker="S2"), selected,
                      segment("后话", id="after", start=3.05, end=4, speaker="S3"), seconds=5)
        result = align_quotes([quote("欢迎大家")], [item])[0]
        self.assertEqual((result["start"], result["end"]), (0.95, 3.05))

    def test_actual_best_score_matches_spec_not_raw_edit_count(self):
        for target, transcript in (("aaa", "aabaa"), ("abcd", "axxbxxcxxd"),
                                   ("abcd", "dxcbxa"), ("abcde", "abcxyzde")):
            with self.subTest(target=target, transcript=transcript):
                expected = reference_best(target, transcript)
                result = align_quotes([quote(target)], [upload(segment(transcript))])[0]
                self.assertEqual(result["score"], expected)
                if expected < MATCH_LOW:
                    self.assertIsNone(result["source"])
                else:
                    self.assertEqual(result["asr_text"], transcript)
                    self.assertEqual(quote_text_is_contiguous(target, result["source"]), target in transcript)

    def test_seeded_short_strings_match_exhaustive_substring_score_oracle(self):
        import random

        rng = random.Random(628)
        for case in range(90):
            target = "".join(rng.choices("abcd", k=rng.randint(1, 9)))
            transcript = "".join(rng.choices("abcdef", k=rng.randint(1, 12)))
            expected = reference_best(target, transcript)
            with self.subTest(case=case, target=target, transcript=transcript):
                result = align_quotes([quote(target)], [upload(segment(transcript))])[0]
                self.assertEqual(result["score"], expected)
                self.assertEqual(result["source"] is not None, expected >= MATCH_LOW)
                if result["source"] is not None:
                    self.assertEqual(result["asr_text"], transcript)
                    self.assertEqual(result["source"]["words"], [])
                    self.assertEqual(quote_text_is_contiguous(target, result["source"]), target in transcript)

    def test_containment_over_sixty_four_characters_keeps_full_score_and_evidence(self):
        target = "abcdefghijklmnopqrstuvwx" * 4
        transcript = "zz" + target[:57] + "y" + target[58:] + "zz"
        result = align_quotes([quote(target)], [upload(segment(transcript))])[0]
        self.assertEqual(result["score"], reference_best(target, transcript))
        self.assertEqual(result["source"]["precision"], "segment")
        self.assertEqual(result["asr_text"], transcript)
        assert_original_blocked(self, target, result)

    def test_partial_word_evidence_across_segments_remains_segment_precision(self):
        sources = [upload(segment("今天", id="a", start=0, end=1,
                                  words=[{"w": "今天", "s": 0, "e": 1}]),
                          segment("欢迎大家", id="b", start=1.1, end=3))]
        result = align_quotes([quote("今天欢迎大家")], sources)[0]
        self.assertEqual(result["score"], 1)
        self.assertEqual(result["source"]["precision"], "segment")
        self.assertEqual(result["source"]["words"], [])

    def test_asr_confidence_is_not_a_fabricated_lexical_score(self):
        source = segment("今天开放")
        source["confidence"] = 0.1
        self.assertEqual(align_quotes([quote("今天开放")], [upload(source)])[0]["score"], 1.0)

    def test_repeated_input_results_have_independent_serialized_words(self):
        source = upload(segment("今天开放", words=[{"w": "今天开放", "s": 1, "e": 4}]))
        result = align_quotes([quote("今天开放", idx=1), quote("今天开放", idx=2)], [source])
        result[0]["source"]["words"][0]["w"] = "changed by caller"
        self.assertEqual(result[1]["source"]["words"][0]["w"], "今天开放")
        self.assertEqual(source["transcript"][0]["words"][0]["w"], "今天开放")

    def test_real_word_boundaries_are_respected_during_search_not_just_after_it(self):
        # The containing whole word legitimately scores 1; no interior clocks.
        # The separate imperfect whole-word alternative must remain available.
        item = upload(segment("xxxxabcdefxxxx。abcxef", words=[
            {"w": "xxxxabcdefxxxx", "s": 0.2, "e": 2.4},
            {"w": "abcxef", "s": 3.1, "e": 5.7}]))
        result = align_quotes([quote("abcdef")], [item])[0]
        self.assertEqual(result["asr_text"], "xxxxabcdefxxxx。")
        self.assertEqual(result["source"]["words"], item["transcript"][0]["words"][:1])
        self.assertEqual((result["start"], result["end"]), (0.2 - 0.12, 2.4 + 0.2))
        self.assertEqual(result["score"], reference_similarity("abcdef", "xxxxabcdefxxxx"))
        self.assertEqual(len(result["alt_takes"]), 1)
        alternative = result["alt_takes"][0]
        self.assertEqual(alternative["asr_text"], "abcxef")
        self.assertEqual(alternative["score"], reference_similarity("abcdef", "abcxef"))
        self.assertEqual(alternative["score"], 0.6)
        self.assertEqual(alternative["words"], item["transcript"][0]["words"][1:])
        self.assertFalse(quote_text_is_contiguous("abcdef", alternative))

    def test_invalid_ids_duration_and_duplicate_inputs_fail_explicitly(self):
        cases = [[upload(id="")], [upload(seconds=float("nan"))], [upload(seconds=0)],
                 [upload(segment("内容", end=6), seconds=5)], [upload(), upload()],
                 [upload(segment("甲"), segment("乙"))]]
        for sources in cases:
            with self.subTest(sources=sources):
                with self.assertRaises(ValueError):
                    align_quotes([quote("内容")], sources)
        with self.assertRaises(ValueError):
            align_quotes([quote("甲"), quote("乙")], [])


class FillerBoundaryAlignmentTests(unittest.TestCase):
    """Synthetic word clocks; strict literal evidence keeps fillers significant."""

    text = "就是希望大家过年都能吃上一口家乡味"
    body = "希望大家过年都能吃上一口家乡味"

    def fixture(self, *, timed=True):
        cues = [
            {"w": "前文", "s": 30.0, "e": 30.8},
            {"w": "就是", "s": 31.02, "e": 31.30},
            {"w": self.body, "s": 31.453, "e": 36.2},
            {"w": "啊", "s": 36.4, "e": 36.7},
            {"w": "尾声", "s": 37.0, "e": 37.8},
        ]
        return upload(segment("前文。" + self.text + "，啊。尾声", start=30, end=38,
                              words=cues if timed else [])), cues

    def assert_strict_evidence(self, requested, source, expected):
        # Formatting-only oracle for these Chinese fixtures. Unlike the fuzzy
        # matcher it MUST NOT remove fillers or allow internal edits.
        self.assertEqual(pm._literal(requested).text in pm._literal(source["asr_text"]).text,
                         expected)
        self.assertEqual(quote_text_is_contiguous(requested, source["source"]), expected)

    def test_exact_jiushi_idx5_preserves_original_word_and_clock(self):
        item, cues = self.fixture()
        before = deepcopy(item)
        result = align_quotes([quote(self.text, idx=5)], [item])[0]
        self.assertEqual(result["idx"], 5)
        self.assertEqual(result["asr_text"], self.text + "，")
        self.assertEqual(result["source"]["matched_text"], result["asr_text"])
        self.assertEqual(result["source"]["words"], cues[1:3])
        self.assertEqual((result["start"], result["end"]), (30.9, 36.4))
        self.assertEqual(result["source"]["precision"], "word")
        self.assertEqual(result["score"], 1.0)
        self.assert_strict_evidence(self.text, result, True)
        self.assertEqual(item, before)

    def test_requested_trailing_filler_is_preserved_too(self):
        item, cues = self.fixture()
        requested = self.text + "，啊"
        result = align_quotes([quote(requested)], [item])[0]
        self.assertEqual(result["source"]["words"], cues[1:4])
        self.assertEqual(result["asr_text"], requested + "。")
        self.assertEqual((result["start"], result["end"]), (cues[1]["s"] - 0.12, cues[3]["e"] + 0.2))
        self.assertEqual(result["score"], 1.0)
        self.assert_strict_evidence(requested, result, True)

    def test_exact_sentence_without_formatting_preserves_jiushi_source_onset(self):
        _, cues = self.fixture()
        for hint in (None, SourceHint(upload_id="u1", seg_id="seg")):
            with self.subTest(hint=hint):
                result = align_quotes([quote(self.text, idx=5, source_hint=hint)], [upload(
                    segment(self.text, start=31, end=37, words=cues[1:3]))])[0]
                self.assertEqual(result["asr_text"], self.text)
                self.assertEqual(result["source"]["matched_text"], self.text)
                self.assertEqual(result["source"]["words"], cues[1:3])
                self.assertEqual(result["source"]["words"][0]["s"], 31.02)
                self.assertEqual(result["start"], 30.9)
                self.assertEqual(result["score"], 1.0)

    def test_multiple_requested_fillers_preserve_split_word_clocks(self):
        text = "嗯，就是希望大家过年都能吃上一口家乡味，啊，呃"
        cues = [{"w": "嗯", "s": 1.0, "e": 1.2}, {"w": "就", "s": 1.3, "e": 1.5},
                {"w": "是", "s": 1.6, "e": 1.8}, {"w": self.body, "s": 2.0, "e": 4.7},
                {"w": "啊", "s": 5.0, "e": 5.2}, {"w": "呃", "s": 5.3, "e": 5.6}]
        result = align_quotes([quote(text)], [upload(segment(text, words=cues))])[0]
        self.assertEqual(result["asr_text"], text)
        self.assertEqual(result["source"]["words"], cues)
        self.assertEqual(result["score"], 1.0)
        self.assert_strict_evidence(text, result, True)

    def test_restored_edge_cannot_split_word_and_keeps_normative_perfect_score(self):
        text = "前文。" + self.text
        cues = [{"w": "前文就是", "s": 1, "e": 2}, {"w": self.body, "s": 2.2, "e": 5}]
        result = align_quotes([quote(self.text)], [upload(segment(text, words=cues))])[0]
        self.assertEqual(result["source"]["words"], cues)
        self.assertEqual(result["asr_text"], text)
        q, actual = normalize_text(self.text), normalize_text(text)
        self.assertEqual(result["score"], reference_similarity(q, actual))
        self.assertEqual(result["score"], 1.0)
        self.assertEqual((result["start"], result["end"]), (0.88, 5.2))
        self.assert_strict_evidence(self.text, result, True)

    def test_unrequested_fillers_are_not_added(self):
        item, cues = self.fixture()
        result = align_quotes([quote(self.body)], [item])[0]
        self.assertEqual(result["source"]["words"], cues[2:3])
        self.assertEqual(result["asr_text"], self.body + "，")
        self.assertEqual(result["start"], 31.333)

    def test_cache_does_not_merge_queries_with_different_filler_edges(self):
        item, cues = self.fixture()
        for targets in ((self.body, self.text, self.text + "，啊"),
                        (self.text + "，啊", self.text, self.body)):
            with self.subTest(targets=targets):
                results = align_quotes([quote(text, idx=i) for i, text in enumerate(targets)], [item])
                for text, result in zip(targets, results):
                    expected = cues[2:3] if text == self.body else cues[1:4] if text.endswith("啊") else cues[1:3]
                    self.assertEqual(result["source"]["words"], expected)
                    self.assert_strict_evidence(text, result, True)

    def test_missing_fillers_remain_missing_without_fabricated_score(self):
        cues = [{"w": self.body, "s": 31.453, "e": 36.2}]
        for requested in (self.text, self.body + "，啊", self.text + "，啊"):
            with self.subTest(requested=requested):
                result = align_quotes([quote(requested)], [upload(segment(self.body, start=31, end=37, words=cues))])[0]
                self.assertEqual(result["source"]["words"], cues)
                self.assertEqual(result["asr_text"], self.body)
                self.assertEqual(result["score"], 1.0)  # Real filler-insensitive score, NOT admission.
                self.assert_strict_evidence(requested, result, False)

    def test_filler_cannot_be_borrowed_over_intervening_words(self):
        cues = [{"w": "就是", "s": 1, "e": 1.3}, {"w": "今天", "s": 1.5, "e": 2},
                {"w": self.body, "s": 2.2, "e": 5}]
        result = align_quotes([quote(self.text)], [upload(segment("就是今天，" + self.body, words=cues))])[0]
        self.assertEqual(result["source"]["words"], cues[2:])
        self.assert_strict_evidence(self.text, result, False)

    def test_filler_cannot_be_borrowed_from_other_speaker_or_discontinuous_segment(self):
        for identity, start in (("S2", 2.0), ("S1", 10.0), ("", 2.0)):
            with self.subTest(identity=identity, start=start):
                sources = [upload(segment("就是", id="a", end=2, speaker="S1",
                                          words=[{"w": "就是", "s": 1, "e": 2}]),
                                  segment(self.body, id="b", start=start, end=start + 4, speaker=identity,
                                          words=[{"w": self.body, "s": start, "e": start + 4}]))]
                result = align_quotes([quote(self.text)], sources)[0]
                self.assertEqual(result["source"]["segment_ids"], ["b"])
                self.assertEqual(result["asr_text"], self.body)
                self.assert_strict_evidence(self.text, result, False)

    def test_continuous_same_speaker_filler_segment_keeps_its_clock(self):
        cues = [{"w": "就是", "s": 1, "e": 2}, {"w": self.body, "s": 2.1, "e": 5}]
        result = align_quotes([quote(self.text)], [upload(
            segment("就是", id="a", start=1, end=2, words=cues[:1]),
            segment(self.body, id="b", start=2.1, end=5, words=cues[1:]))])[0]
        self.assertEqual(result["source"]["segment_ids"], ["a", "b"])
        self.assertEqual(result["source"]["words"], cues)
        self.assertEqual(result["start"], 0.88)
        self.assert_strict_evidence(self.text, result, True)

    def test_untimed_source_keeps_entire_segment_and_no_synthetic_words(self):
        item, _ = self.fixture(timed=False)
        result = align_quotes([quote(self.text)], [item])[0]
        self.assertEqual(result["asr_text"], item["transcript"][0]["text"])
        self.assertEqual(result["source"]["matched_text"], self.text)
        self.assertEqual(result["source"]["words"], [])
        self.assertEqual(result["source"]["precision"], "segment")
        self.assertEqual((result["start"], result["end"]), (30, 38))

    def test_insertion_and_internal_deletions_remain_rejected(self):
        item, _ = self.fixture()
        for requested in (self.text.replace("过年", "今年过年"),
                          self.text.replace("过年", "")):
            with self.subTest(requested=requested):
                result = align_quotes([quote(requested)], [item])[0]
                self.assert_strict_evidence(requested, result, False)
                result["text"] = requested
                self.assertIn("QUOTE_NONCONTIGUOUS", {issue["code"] for issue in
                              evaluate_mode_checks([result], [], "original", {})})
                q, actual = normalize_text(requested), normalize_text(result["source"]["matched_text"])
                self.assertEqual(result["score"], reference_similarity(q, actual))
                assert_original_blocked(self, requested, result)
        internal = "就是希望大家，嗯，过年都能吃上一口家乡味"
        result = align_quotes([quote(self.text)], [upload(segment(internal))])[0]
        self.assertEqual(result["asr_text"], internal)
        self.assert_strict_evidence(self.text, result, False)


class IdentitySafetyTests(unittest.TestCase):
    def test_unknown_speaker_ids_do_not_join_even_with_real_word_fields(self):
        for identity in ("", " "):
            for timed in (False, True):
                with self.subTest(identity=identity, timed=timed):
                    sources = [upload(segment("甲乙丙丁", id="a", end=2, speaker=identity,
                                              words=[{"w": "甲乙丙丁", "s": 0, "e": 2}] if timed else []),
                                      segment("戊己庚辛", id="b", start=2, end=4, speaker=identity,
                                              words=[{"w": "戊己庚辛", "s": 2, "e": 4}] if timed else []))]
                    result = align_quotes([quote("甲乙丙丁戊己庚辛")], sources)[0]
                    self.assertEqual(result["score"], 1.0)
                    self.assertEqual(result["source"]["segment_ids"], ["a"])
                    self.assertEqual(result["speaker_id"], identity)
                    self.assertEqual(result["asr_text"], "甲乙丙丁")
                    self.assertEqual(result["source"]["words"], sources[0]["transcript"][0]["words"])
                    self.assertEqual(result["alt_takes"], [])
                    assert_original_blocked(self, "甲乙丙丁戊己庚辛", result)

    def test_nonempty_identical_id_joins_without_named_speaker_record(self):
        sources = [upload(segment("甲乙丙丁", id="a", end=2, speaker="opaque"),
                          segment("戊己庚辛", id="b", start=2, end=4, speaker="opaque"))]
        result = align_quotes([quote("甲乙丙丁戊己庚辛")], sources, [Speaker(id="opaque")])[0]
        self.assertEqual(result["score"], 1)
        self.assertEqual(result["source"]["segment_ids"], ["a", "b"])

    def test_unknown_alternatives_never_cross_segment_or_upload(self):
        sources = [upload(segment("欢迎大家", speaker=""), id="a"),
                   upload(segment("欢迎大家", speaker=""), id="b"),
                   upload(segment("欢迎大家", speaker="", id="s1", end=2),
                          segment("欢迎大家", speaker="", id="s2", start=3, end=5), id="c")]
        result = align_quotes([quote("欢迎大家")], sources)[0]
        self.assertEqual(result["speaker_id"], "")
        self.assertEqual(result["alt_takes"], [])

    def test_unknown_same_segment_distinct_word_takes_are_not_named(self):
        cues = [{"w": "欢迎大家", "s": 1, "e": 2}, {"w": "欢迎大家", "s": 4, "e": 5}]
        result = align_quotes([quote("欢迎大家")], [upload(segment("欢迎大家，欢迎大家", speaker="", words=cues))])[0]
        self.assertEqual(result["alt_takes"], [])  # v2 requires a KNOWN person, even within one segment.
        self.assertEqual(result["speaker_id"], "")
        self.assertEqual(result["source"]["segment_ids"], ["seg"])
        self.assertEqual(result["source"]["words"], cues[:1])
        self.assertEqual(result["asr_text"], "欢迎大家，")
        self.assertEqual((result["start"], result["end"]), (0.88, 2.2))

    def test_known_same_speaker_alternatives_can_cross_uploads(self):
        sources = [upload(segment("今天正式开放欢迎大家参观", speaker="S1"), id="a"),
                   upload(segment("今天正式开放欢迎大家参馆", speaker="S1"), id="b"),
                   upload(segment("今天正式开放欢迎大家参观", speaker="S2"), id="c")]
        result = align_quotes([quote("今天正式开放欢迎大家参观")], sources)[0]
        self.assertEqual([t["upload_id"] for t in result["alt_takes"]], ["b"])
        alternative = result["alt_takes"][0]
        self.assertEqual(alternative["score"], reference_best("今天正式开放欢迎大家参观", "今天正式开放欢迎大家参馆"))
        self.assertEqual(alternative["asr_text"], "今天正式开放欢迎大家参馆")
        self.assertEqual(alternative["speaker_id"], "S1")
        self.assertFalse(quote_text_is_contiguous("今天正式开放欢迎大家参观", alternative))

    def test_hinted_speaker_inexact_local_match_cannot_be_stolen_by_exact_other(self):
        sources = [upload(segment("今天正式开放欢迎大家参馆", id="near", speaker="S1", start=10, end=14),
                          segment("今天正式开放欢迎大家参观", id="far", speaker="S2", start=40, end=44, snr=40))]
        result = align_quotes([quote("今天正式开放欢迎大家参观", speaker_hint="S1",
                                    source_hint=SourceHint(upload_id="u1", seg_id="near"))], sources)[0]
        self.assertEqual(result["speaker_id"], "S1")
        self.assertEqual(result["start"], 10)
        self.assertEqual(result["score"], reference_best("今天正式开放欢迎大家参观", "今天正式开放欢迎大家参馆"))
        self.assertEqual(result["alt_takes"], [])
        self.assertEqual(result["asr_text"], "今天正式开放欢迎大家参馆")
        assert_original_blocked(self, "今天正式开放欢迎大家参观", result)

    def test_missing_hint_identity_does_not_promote_low_score(self):
        sources = [upload(segment("甲壬癸子丑", speaker="S1")),
                   upload(segment("甲乙丙丁戊", speaker="S2"), id="b")]
        result = align_quotes([quote("甲乙丙丁戊", speaker_hint="absent")], sources)[0]
        self.assertEqual(result["speaker_id"], "S2")
        self.assertEqual(result["score"], 1)

    def test_null_words_are_absent_but_malformed_words_are_rejected(self):
        source = segment("原声全文")
        source["words"] = None
        result = align_quotes([quote("原声全文")], [upload(source)])[0]
        self.assertEqual(result["source"]["precision"], "segment")
        self.assertEqual(result["source"]["words"], [])
        for invalid in ("bad", [None], [{"text": "原声全文"}]):
            with self.subTest(invalid=invalid):
                source["words"] = invalid
                with self.assertRaises(ValueError):
                    align_quotes([quote("原声全文")], [upload(source)])


class ContiguousQuoteTests(unittest.TestCase):
    def test_confirmed_trim_text_passes_but_trim_flag_cannot_waive_rewrite(self):
        source = take()
        before = source.model_dump(mode="json")
        trimmed = validate_quote_trim(source, 1.6, 6.5)
        for gate in ("warn", "block"):
            item = row(0, text=trimmed["asr_text"], source=trimmed, trim={"start": 1.6, "end": 6.5})
            issues = evaluate_mode_checks([item], [], "original", {}, gate)
            self.assertNotIn("QUOTE_NONCONTIGUOUS", {i["code"] for i in issues})
            for text in (source.asr_text, "今天大家。", "今天不欢迎大家。"):
                with self.subTest(gate=gate, text=text):
                    item["text"] = text
                    issues = evaluate_mode_checks([item], [], "original", {}, gate)
                    issue = next(i for i in issues if i["code"] == "QUOTE_NONCONTIGUOUS")
                    self.assertEqual((issue["level"], issue["severity"]), (0, "error"))
        self.assertEqual(source.model_dump(mode="json"), before)

    def test_source_asr_not_matched_text_controls_contiguity(self):
        source = take().model_copy(update={"matched_text": "新编原话"})
        self.assertTrue(quote_text_is_contiguous("今天欢迎", source))
        self.assertFalse(quote_text_is_contiguous("新编原话", source))
        self.assertFalse(quote_text_is_contiguous("我们大家", source))

    def test_equivalent_numbers_and_leading_fillers_are_allowed(self):
        source = {"asr_text": "嗯，就是说，我们一月三十一号开放，欢迎大家。"}
        self.assertTrue(quote_text_is_contiguous("我们1月31日开放", source))
        self.assertTrue(quote_text_is_contiguous("欢迎大家", source))

    def test_empty_or_absent_asr_never_proves_contiguous(self):
        for text, source in (("", {"asr_text": "原话"}), ("嗯，啊", {"asr_text": "嗯，啊"}),
                             ("原话", {}), ("原话", {"asr_text": None})):
            self.assertFalse(quote_text_is_contiguous(text, source))

    def test_original_blocks_negation_deletion_under_ten_percent(self):
        item = row(7, text="我们认为今天这项活动应该继续举行")
        item["source"]["asr_text"] = "我们认为今天这项活动不应该继续举行"
        before = deepcopy(item)
        for gate in ("warn", "block"):
            issues = {v["code"]: v for v in evaluate_mode_checks([item], [], "original", {}, gate)}
            self.assertEqual(issues["QUOTE_NONCONTIGUOUS"]["severity"], "error")
            self.assertEqual(issues["QUOTE_NONCONTIGUOUS"]["level"], 0)
            self.assertEqual(issues["QUOTE_NONCONTIGUOUS"]["sentence_id"], 7)
            self.assertIn("QUOTE_TEXT_DIFFERS", issues)
        self.assertEqual(item, before)

    def test_original_blocks_insertion_homophone_and_middle_deletion(self):
        source = "今天市集正式开放欢迎大家前来参观"
        for requested in ("今天市集正式开放欢迎大冢前来参观", "今天市集正式开放热烈欢迎大家前来参观",
                          "今天市集开放欢迎大家前来参观"):
            with self.subTest(requested=requested):
                aligned = align_quotes([quote(requested)], [upload(segment(source))])[0]
                self.assertGreaterEqual(aligned["score"], MATCH_LOW)
                self.assertEqual(aligned["asr_text"], source)
                aligned["text"] = requested
                issues = {v["code"] for v in evaluate_mode_checks([aligned], [], "original", {})}
                self.assertIn("QUOTE_NONCONTIGUOUS", issues)
                self.assertIn("QUOTE_TEXT_DIFFERS", issues)

    def test_original_contiguous_substring_does_not_block_segment_precision(self):
        item = row(0, text="今天开放")
        item["source"]["asr_text"] = "嗯，我们今天开放，欢迎大家"
        issues = evaluate_mode_checks([item], [], "original", {})
        self.assertNotIn("QUOTE_NONCONTIGUOUS", {v["code"] for v in issues})

    def test_mixed_keeps_ten_percent_warning_and_never_original_block(self):
        item = row(0, text="我们认为今天这项活动应该继续举行")
        item["source"]["asr_text"] = "我们认为今天这项活动不应该继续举行"
        issues = {v["code"] for v in evaluate_mode_checks([item], [], "mixed", {})}
        self.assertIn("QUOTE_TEXT_DIFFERS", issues)
        self.assertNotIn("QUOTE_NONCONTIGUOUS", issues)


class SearchWorkTests(unittest.TestCase):
    def test_spec_formula_multiset_multiplicity_empty_and_singletons(self):
        for a, b, expected in (("", "a", 0.0), ("a", "", 0.0), ("a", "ba", 1.0),
                               ("a", "bc", 0.0), ("aaaa", "aaab", 2 / 3),
                               ("abcd", "cdab", 2 / 3), ("abcdef", "abcxef", 3 / 5)):
            with self.subTest(a=a, b=b):
                self.assertEqual(reference_similarity(a, b), expected)
                self.assertEqual(pm.similarity(a, b), expected)
                self.assertEqual(pm.similarity(b, a), expected)

    def test_exhaustive_spec_oracle_all_short_strings_and_legal_boundary_subsets(self):
        import itertools

        values = ["".join(chars) for size in range(1, 5)
                  for chars in itertools.product("ab", repeat=size)]
        cases = 0
        for query, text in itertools.product(values, repeat=2):
            for mask in range(1 << (len(text) - 1)):
                boundaries = (0, *(i for i in range(1, len(text)) if mask & (1 << (i - 1))), len(text))
                legal = [(a, b, reference_similarity(query, text[a:b]))
                         for a in boundaries for b in boundaries if b > a]
                expected = max(score for _, _, score in legal)
                with self.subTest(query=query, text=text, boundaries=boundaries):
                    for best_only in (False, True):
                        spans = pm._local_spans(query, text, boundaries, best_only=best_only)
                        self.assertEqual(max((score for _, _, score in spans), default=0.0), expected)
                        for a, b, score in spans:
                            self.assertIn(a, boundaries)
                            self.assertIn(b, boundaries)
                            self.assertEqual(score, reference_similarity(query, text[a:b]))
                            self.assertEqual(score, max(v for start, _, v in legal if start == a))
                        if best_only and len(text) <= len(query) and expected == 1.0:
                            perfect = min((v for v in legal if v[2] == 1.0),
                                          key=lambda v: (abs(v[1] - v[0] - len(query)), v[0], v[1]))
                            self.assertEqual(spans, [perfect])
                cases += 1
        self.assertEqual(cases, 5100)

    def test_seeded_legal_word_spans_keep_fractional_scores_and_full_maxima(self):
        import random

        rng = random.Random(929)
        for case in range(180):
            query = "".join(rng.choices("abc", k=rng.randint(1, 10)))
            text = "".join(rng.choices("abcd", k=rng.randint(1, 14)))
            boundaries = (0, *(i for i in range(1, len(text)) if rng.choice((False, True))), len(text))
            with self.subTest(case=case):
                expected = reference_best(query, text, boundaries)
                for best_only in (False, True):
                    spans = pm._local_spans(query, text, boundaries, best_only=best_only)
                    self.assertEqual(max((v for _, _, v in spans), default=0.0), expected)
                    for a, b, score in spans:
                        self.assertIn(a, boundaries)
                        self.assertIn(b, boundaries)
                        self.assertEqual(score, reference_similarity(query, text[a:b]))

    def test_character_disjoint_missing_source_preserves_null_projection(self):
        # Additional negative fixture, NOT a replacement for the original
        # shared-character/demo high-score counterexamples above.
        result = align_quotes([quote("甲乙丙")], [upload(segment("戊己庚"))])[0]
        self.assertEqual(result["score"], reference_best("甲乙丙", "戊己庚"))
        self.assertEqual(result["score"], 0.0)
        for key in ("source", "upload_id", "start", "end", "speaker_id", "asr_text"):
            self.assertIsNone(result[key])
        self.assertEqual(result["alt_takes"], [])

    def test_perfect_bound_fast_path_has_deterministic_work_and_no_partial_success(self):
        query = "abcdefghijklmnopqrst" * 100
        text = query[:1000] + "z" + query[1001:]
        self.assertEqual(pm.MAX_SEARCH_STEPS, 1_000_000)
        budget = pm._SearchBudget(4000)
        self.assertEqual(pm._local_spans(query, text, budget=budget, best_only=True), [(0, 1000, 1.0)])
        self.assertEqual(budget.remaining, 0)
        exhausted = pm._SearchBudget(3999)
        with self.assertRaisesRegex(ValueError, "计算上限"):
            pm._local_spans(query, text, budget=exhausted, best_only=True)
        self.assertEqual(exhausted.remaining, -1)
        # No perfect LEGAL whole-word span: exhaustive fallback must retain
        # 2/3 rather than return a partial singleton's 1 or fabricate endpoints.
        self.assertEqual(pm._local_spans("abcd", "cdab", (0, 4), best_only=True), [(0, 4, 2 / 3)])

    def test_exact_distance_matches_independent_matrix_including_long_vectors(self):
        import random
        rng = random.Random(928)
        for size in (0, 1, 4, 10, 65, 129):
            for _ in range(8):
                a = "".join(rng.choices("abcd", k=size))
                b = "".join(rng.choices("abcd", k=size + 3))
                self.assertEqual(pm._distance(a, b), reference_distance(a, b))

    def test_best_only_bounds_match_exhaustive_spec_oracle(self):
        import random
        rng = random.Random(929)
        for case in range(180):
            query = "".join(rng.choices("abc", k=rng.randint(1, 10)))
            text = "".join(rng.choices("abcd", k=rng.randint(1, 14)))
            expected = reference_best(query, text)
            spans = pm._local_spans(query, text, best_only=True)
            with self.subTest(case=case):
                self.assertEqual(max((score for _, _, score in spans), default=0), expected)
                for a, b, score in spans:
                    self.assertEqual(score, reference_similarity(query, text[a:b]))

    def test_legal_word_boundaries_preserve_inexact_candidate_scores(self):
        query, text, boundaries = "abcdef", "xxxxabcdefxxxxabcxef", (0, 14, 20)
        text = text[:19]
        boundaries = (0, 14, len(text))
        spans = pm._local_spans(query, text, boundaries)
        expected = reference_best(query, text, boundaries)
        self.assertEqual(max(score for _, _, score in spans), expected)
        for a, b, score in spans:
            self.assertIn(a, boundaries)
            self.assertIn(b, boundaries)
            self.assertEqual(score, reference_similarity(query, text[a:b]))

    def test_exact_single_untimed_take_skips_fuzzy_search(self):
        with patch.object(pm, "_local_spans", side_effect=AssertionError("no fuzzy search")):
            result = align_quotes([quote("今天开放")], [upload(segment("前言今天开放尾声"))])[0]
        self.assertEqual(result["score"], 1)
        self.assertEqual(result["asr_text"], "前言今天开放尾声")

    def test_inexact_untimed_take_materialized_once_and_cached_per_query(self):
        with patch.object(pm, "_candidate", wraps=pm._candidate) as candidates:
            result = align_quotes([quote("今天开放欢迎大家", idx=i) for i in range(4)],
                                  [upload(segment("前话今天开放欢迎大冢尾声"))])
        self.assertEqual(candidates.call_count, 1)
        self.assertEqual(len(result), 4)
        self.assertEqual(result[0]["score"], reference_best("今天开放欢迎大家", "前话今天开放欢迎大冢尾声"))
        for value in result:
            self.assertEqual(value["asr_text"], "前话今天开放欢迎大冢尾声")
            self.assertEqual(value["source"]["words"], [])
            assert_original_blocked(self, "今天开放欢迎大家", value)

    def test_hint_physically_slices_first_pass_and_does_not_scan_global_text(self):
        sources = [upload(*(segment("欢迎大家" if i == 50 else "背景介绍", id=str(i),
                                    start=i * 10, end=i * 10 + 2) for i in range(100)), seconds=1000)]
        lengths = []
        real = pm._stream_candidates
        def observed(stream, query, budget):
            lengths.append(len(stream.normalized.text))
            return real(stream, query, budget)
        with patch.object(pm, "_stream_candidates", side_effect=observed):
            result = align_quotes([quote("欢迎大家", source_hint=SourceHint(upload_id="u1", seg_id="50"))], sources)[0]
        self.assertEqual(result["start"], 500)
        self.assertEqual(lengths, [4])

    def test_hinted_word_stream_search_is_sliced_without_inventing_times(self):
        cues = [{"w": "前话", "s": 1, "e": 2}, {"w": "欢迎大家", "s": 50, "e": 52},
                {"w": "后话", "s": 98, "e": 99}]
        streams, _ = pm._streams([upload(segment("前话欢迎大家后话", end=100, words=cues))])
        local = pm._region_stream(streams[0], 45, 57)
        self.assertIsNotNone(local)
        assert local is not None
        self.assertEqual(local.normalized.text, "欢迎大家")
        candidate = pm._stream_candidates(local, "欢迎大家", pm._SearchBudget())[0]
        self.assertEqual(candidate.take.words, [Word(**cues[1])])

    def test_work_budget_rejects_not_partial_candidate_success(self):
        with self.assertRaisesRegex(ValueError, "计算上限"):
            pm._local_spans("a" * 2000, "ab" * 2000, budget=pm._SearchBudget(100))

    def test_script_hard_limit_parse_and_alignment(self):
        with self.assertRaisesRegex(ValueError, "8000"):
            parse_sentences("字" * 8001, "original")
        with self.assertRaisesRegex(ValueError, "8000"):
            align_quotes([quote("字" * 2000, idx=i) for i in range(5)], [])
        self.assertEqual(len(align_quotes([quote("字" * 2000, idx=i) for i in range(4)], [])), 4)

    def test_transcript_aggregate_limits_fail_before_search(self):
        with patch.object(pm, "_stream_candidates", side_effect=AssertionError("no search")):
            for sources in ([upload(seconds=3600.01)], [upload(seconds=1801), upload(id="b", seconds=1800)],
                            [upload(segment("字" * 200001))],
                            [upload(segment("字" * 100001)), upload(segment("字" * 100000), id="b")]):
                with self.subTest(seconds=sources[0]["sec"]):
                    with self.assertRaises(ValueError):
                        align_quotes([quote("字")], sources)

    def test_2000_char_60_minute_exact_benchmark_and_evidence_limits(self):
        query = "欢迎参观采访活动" * 250
        sources = [upload(segment("背景" * 99000 + query, end=3600), seconds=3600)]
        started = time.perf_counter()
        result = align_quotes([quote(query)], sources)[0]
        elapsed = time.perf_counter() - started
        print(f"BENCH exact query=2000 transcript=200000 duration=3600 elapsed_ms={elapsed * 1000:.3f}")
        self.assertEqual(result["score"], 1)
        self.assertEqual(result["source"]["precision"], "segment")
        self.assertEqual(result["source"]["words"], [])
        self.assertEqual((result["start"], result["end"]), (0, 3600))
        # Generous regression guard, NOT a claim of a 200ms service guarantee.
        self.assertLess(elapsed, 10)

    def test_2000_char_inexact_adversarial_work_is_bounded(self):
        started = time.perf_counter()
        with self.assertRaisesRegex(ValueError, "计算上限"):
            align_quotes([quote("a" * 2000)], [upload(segment("ab" * 100000, end=3600), seconds=3600)])
        elapsed = time.perf_counter() - started
        print(f"BENCH bounded_rejection query=2000 transcript=200000 elapsed_ms={elapsed * 1000:.3f}")
        self.assertLess(elapsed, 10)

    def test_2000_char_inexact_near_match_is_not_rejected_or_rounded(self):
        query = "abcdefghijklmnopqrst" * 100
        text = query[:1000] + "z" + query[1001:]
        started = time.perf_counter()
        result = align_quotes([quote(query)], [upload(segment(text))])[0]
        elapsed = time.perf_counter() - started
        print(f"BENCH inexact query=2000 transcript=2000 elapsed_ms={elapsed * 1000:.3f}")
        # This unchanged untimed fixture has a legal exact 1000-character
        # prefix: §10.3's maximum is 1, NOT 0.9995 edit similarity.
        self.assertEqual(result["score"], reference_similarity(query, text[:1000]))
        self.assertEqual(result["score"], 1.0)
        self.assertEqual(result["asr_text"], text)
        self.assertEqual(result["source"]["matched_text"], text[:1000])
        self.assertEqual(result["source"]["words"], [])
        assert_original_blocked(self, query, result)
        # Separate genuine indivisible evidence retains the fractional full
        # score, without changing the original untimed fixture to force it low.
        cues = [{"w": text, "s": 0, "e": 6}]
        whole = align_quotes([quote(query)], [upload(segment(text, words=cues))])[0]
        self.assertEqual(whole["score"], reference_similarity(query, text))
        self.assertEqual(whole["score"], 1997 / 1999)
        self.assertNotEqual(whole["score"], round(whole["score"], 3))
        self.assertEqual(whole["source"]["words"], cues)
        assert_original_blocked(self, query, whole)
        self.assertLess(elapsed, 10)

    def test_number_heavy_normalization_keeps_source_mapping(self):
        text = "三十一号 " * 20000
        started = time.perf_counter()
        normalized = pm._normalize_with_mapping(text)
        elapsed = time.perf_counter() - started
        self.assertEqual(normalized.text, "31号" * 20000)
        self.assertEqual(text[slice(*normalized.spans[-3])], "三十一")
        print(f"BENCH normalization_numeric chars={len(text)} elapsed_ms={elapsed * 1000:.3f}")
        self.assertLess(elapsed, 10)


class CutTests(unittest.TestCase):
    def test_handles_are_120_and_200_ms(self):
        self.assertEqual(refine_cut([Word(w="词", s=2, e=3)], 2, 3, 10), (1.88, 3.2))

    def test_refine_never_exceeds_source_or_cuts_adjacent_words(self):
        cues = [Word(w="前", s=0, e=1.95), Word(w="选中", s=2, e=3), Word(w="后", s=3.1, e=4)]
        self.assertEqual(refine_cut(cues, 2, 3, 4), (1.95, 3.1))
        self.assertEqual(refine_cut([Word(w="全部", s=0, e=4)], 0.2, 3.8, 4), (0, 4))

    def test_snap_to_nearest_safe_silence_within_300_ms(self):
        quiet = [(1.6, 1.7), (1.0, 1.1), (3.3, 3.4)]
        before = deepcopy(quiet)
        self.assertEqual(refine_cut([Word(w="词", s=2, e=3)], 2, 3, 5, quiet), (1.7, 3.3))
        self.assertEqual(quiet, before)

    def test_far_or_speech_overlapping_silence_not_used(self):
        words = [Word(w="词", s=2, e=3)]
        self.assertEqual(refine_cut(words, 2, 3, 5, [(1, 1.2), (3.6, 3.8)]), (1.88, 3.2))
        self.assertEqual(refine_cut(words, 2, 3, 5, [(1.7, 2.1), (2.9, 3.5)]), (1.88, 3.2))

    def test_refine_empty_words_has_no_inferred_word_boundaries(self):
        self.assertEqual(refine_cut([], 1, 4, 5), (1, 4))

    def test_invalid_ranges_and_word_times_fail(self):
        for a, b, duration in ((-1, 3, 5), (1, 1, 5), (2, 1, 5), (1, 6, 5),
                               (float("nan"), 3, 5), (1, 3, float("inf")), (True, 3, 5)):
            with self.subTest(a=a, b=b, duration=duration):
                with self.assertRaises(ValueError):
                    refine_cut([], a, b, duration)
        with self.assertRaises(ValueError):
            refine_cut([Word(w="前", s=1, e=3), Word(w="后", s=2, e=4)], 1, 4, 5)
        with self.assertRaises(ValueError):
            refine_cut([], 1, 3, 5, [(0, float("nan"))])

    def test_trim_contiguous_words_preserves_actual_text_punctuation_and_times(self):
        source = take()
        before = source.model_dump()
        result = validate_quote_trim(source, 1.6, 3.7)
        self.assertEqual(result["asr_text"], "今天欢迎")
        self.assertEqual(result["words"], [w.model_dump() for w in source.words[1:3]])
        self.assertEqual((result["start"], result["end"]), (1.6, 3.7))
        self.assertEqual(result["score"], source.score)
        self.assertEqual(source.model_dump(), before)
        self.assertEqual(result["take_id"], validate_quote_trim(source, 1.6, 3.7)["take_id"])

    def test_trim_rejects_expansion_short_nan_infinity_and_word_interior(self):
        for a, b in ((0.7, 6), (1, 6.6), (2, 3.7), (1.6, 3.5), (3.2, 3.7),
                     (2, 1), (float("nan"), 4), (1, float("inf")), (True, 4)):
            with self.subTest(a=a, b=b):
                with self.assertRaises(ValueError):
                    validate_quote_trim(take(), a, b)

    def test_trim_cannot_inject_new_text_or_remove_middle_words(self):
        with self.assertRaises(TypeError):
            validate_quote_trim(take(), 1.0, 6.2, text="今天新字大家")
        result = validate_quote_trim(take(), 1.0, 6.2)
        self.assertEqual(result["asr_text"], "我们，今天欢迎大家。")
        forged = take().model_dump()
        forged["words"].pop(1)
        with self.assertRaises(ValueError):
            validate_quote_trim(QuoteTake(**forged), 1.0, 6.2)

    def test_exact_one_second_trim_at_fractional_source_clock(self):
        source = QuoteTake(take_id="t", upload_id="u", start=1.1, end=2.5,
                           speaker_id="S1", asr_text="原话", score=1,
                           words=[Word(w="原话", s=1.3, e=2.3)])
        result = validate_quote_trim(source, 1.3, 2.3)
        self.assertEqual((result["start"], result["end"]), (1.3, 2.3))

    def test_segment_precision_only_allows_unchanged_range(self):
        source = QuoteTake(take_id="t", upload_id="u", start=1, end=5,
                           speaker_id="S1", asr_text="整段，没有词时间", score=1)
        self.assertEqual(validate_quote_trim(source, 1, 5), source.model_dump())
        with self.assertRaises(ValueError):
            validate_quote_trim(source, 2, 5)


class JumpCutTests(unittest.TestCase):
    def test_contiguous_positive_gap_at_most_half_second_not_counted(self):
        for gap in (0, 0.1, 0.5):
            with self.subTest(gap=gap):
                self.assertEqual(calculate_jumpcuts([row(8), row(9, start=2 + gap, end=4)]), [])

    def test_half_second_fractional_clock_not_misread_as_discontinuity(self):
        self.assertEqual(calculate_jumpcuts([row(0, start=0, end=0.6), row(1, start=1.1, end=3)]), [])

    def test_negative_gap_is_jump_even_when_absolute_gap_below_half_second(self):
        result = calculate_jumpcuts([row(8), row(9, start=1.9, end=4)], "hard")
        self.assertEqual([cut.model_dump() for cut in result], [{"after_row": 8, "cover": "hard", "shot": None, "downgraded": False}])

    def test_different_file_forward_gap_and_reverse_are_jumps(self):
        for after in (row(9, file="u2", start=2, end=4), row(9, start=2.51, end=4), row(9, start=0, end=1)):
            with self.subTest(after=after):
                self.assertEqual(len(calculate_jumpcuts([row(8), after], "zoom")), 1)

    def test_intervening_narration_or_missing_quote_breaks_adjacency(self):
        for middle in ({"idx": 3, "kind": "narration"}, {"idx": 3, "kind": "quote", "source": None}):
            with self.subTest(middle=middle):
                self.assertEqual(calculate_jumpcuts([row(8), middle, row(9, file="u2")]), [])

    def test_broll_is_only_assigned_with_actual_shot_otherwise_downgrade(self):
        result = calculate_jumpcuts([row(2), row(7, file="u2")])[0]
        self.assertEqual((result.cover, result.shot, result.downgraded), ("zoom", None, True))
        result = calculate_jumpcuts([row(2), row(7, file="u2", cover_shot=0)])[0]
        self.assertEqual((result.cover, result.shot, result.downgraded), ("broll", 0, False))

    def test_flat_and_string_source_rows_and_nonsequential_ids(self):
        rows = [{"id": 70, "kind": "quote", "source": "u1", "start": 1, "end": 3},
                {"id": 5, "kind": "quote", "upload_id": "u2", "start": 0, "end": 2}]
        before = deepcopy(rows)
        self.assertEqual(calculate_jumpcuts(rows, "hard")[0].after_row, 70)
        self.assertEqual(rows, before)

    def test_source_identity_with_flat_times(self):
        rows = [{"id": 70, "kind": "quote", "source": {"upload_id": "u1"}, "start": 1, "end": 3},
                {"id": 5, "kind": "quote", "source": {"upload_id": "u2"}, "start": 0, "end": 2}]
        self.assertEqual(calculate_jumpcuts(rows, "hard")[0].after_row, 70)

    def test_invalid_covers_or_source_times_fail(self):
        with self.assertRaises(ValueError):
            calculate_jumpcuts([], "invent")
        with self.assertRaises(ValueError):
            calculate_jumpcuts([row(0), row(1, end=float("nan"))])


class ModeChecksTests(unittest.TestCase):
    def codes(self, rows, **kwargs):
        return {issue["code"]: issue for issue in evaluate_mode_checks(
            rows, kwargs.pop("speakers", []), kwargs.pop("mode", "mixed"),
            kwargs.pop("preferences", {}), **kwargs)}

    def test_match_thresholds_exactly_point_six_and_point_eight_five(self):
        for score, expected in ((0.59, "QUOTE_NOT_FOUND"), (0.6, "QUOTE_MATCH_LOW"),
                                (0.8499, "QUOTE_MATCH_LOW"), (0.85, None), (1, None)):
            with self.subTest(score=score):
                item = row(0)
                item["source"]["score"] = score
                codes = self.codes([item])
                actual = {c for c in codes if c in {"QUOTE_NOT_FOUND", "QUOTE_MATCH_LOW"}}
                self.assertEqual(actual, {expected} if expected else set())

    def test_quote_duration_boundary_matrix(self):
        for seconds, expected, level in ((0.999, "QUOTE_TOO_SHORT", 0), (1, None, None),
                                         (20, None, None), (20.001, "QUOTE_TOO_LONG", 1),
                                         (30, "QUOTE_TOO_LONG", 1), (30.001, "QUOTE_TOO_LONG", 0)):
            with self.subTest(seconds=seconds):
                codes = self.codes([row(0, end=seconds)])
                actual = {c for c in codes if c in {"QUOTE_TOO_SHORT", "QUOTE_TOO_LONG"}}
                self.assertEqual(actual, {expected} if expected else set())
                if expected:
                    self.assertEqual(codes[expected]["level"], level)
                    self.assertEqual(codes[expected]["severity"], "error" if level == 0 else "warning")

    def test_exact_one_second_at_fractional_clock_is_not_blocked(self):
        self.assertNotIn("QUOTE_TOO_SHORT", self.codes([row(0, start=1.3, end=2.3)]))

    def test_snr_unknown_and_exactly_eighteen_are_not_warned(self):
        for snr, expected in ((None, False), (18, False), (17.999, True), (15, True), (14.999, True), (-3, True)):
            with self.subTest(snr=snr):
                item = row(0)
                item["source"]["snr_db"] = snr
                self.assertEqual("QUOTE_AUDIO_NOISY" in self.codes([item]), expected)

    def test_normalized_difference_above_ten_percent(self):
        item = row(0, text="甲乙丙丁戊己庚辛壬癸")
        for actual, expected in (("甲乙丙丁戊己庚辛壬子", False), ("甲乙丙丁戊己庚辛子丑", True)):
            with self.subTest(actual=actual):
                item["source"]["asr_text"] = actual
                self.assertEqual("QUOTE_TEXT_DIFFERS" in self.codes([item]), expected)
        item["text"] = "我们一月三十一号开放"
        item["source"]["asr_text"] = "我们1月31日开放"
        self.assertNotIn("QUOTE_TEXT_DIFFERS", self.codes([item]))

    def test_unmatched_and_invalid_numeric_source_never_looks_successful(self):
        for source in (None, {"upload_id": "u", "asr_text": "今天开放", "score": float("nan")},
                       {"upload_id": "u", "asr_text": "今天开放", "score": 2}):
            with self.subTest(source=source):
                self.assertEqual(self.codes([row(0, source=source)])["QUOTE_NOT_FOUND"]["level"], 0)
        item = row(0, end=float("inf"))
        self.assertEqual(self.codes([item])["QUOTE_INVALID_RANGE"]["level"], 0)

    def test_speaker_unnamed_only_when_lower_third_explicitly_enabled(self):
        people = [Speaker(id="S1", auto_label="说话人1")]
        for preferences, expected in (({}, False), ({"lower_third": False}, False), ({"lower_third": True}, True)):
            with self.subTest(preferences=preferences):
                self.assertEqual("SPEAKER_UNNAMED" in self.codes([row(0)], speakers=people, preferences=preferences), expected)
        named = [Speaker(id="S1", name="王红")]
        self.assertNotIn("SPEAKER_UNNAMED", self.codes([row(0)], speakers=named, preferences={"lower_third": True}))

    def test_repeated_unnamed_speaker_has_one_issue(self):
        issues = evaluate_mode_checks([row(0), row(1)], [], "mixed", {"lower_third": True})
        self.assertEqual(sum(i["code"] == "SPEAKER_UNNAMED" for i in issues), 1)

    def test_all_mixed_and_original_non_broll_jumps_warn(self):
        for mode in ("mixed", "original"):
            for count in (0, 1, 3, 4):
                cuts = [{"after_row": i, "cover": "hard"} for i in range(count)]
                self.assertEqual("JUMP_CUT_UNCOVERED" in self.codes([], mode=mode, jumpcuts=cuts), count > 0)
            for cover, downgraded, expected in (("zoom", False, True), ("zoom", True, True), ("broll", False, False)):
                with self.subTest(mode=mode, cover=cover, downgraded=downgraded):
                    cuts = [{"after_row": 0, "cover": cover, "downgraded": downgraded}]
                    issues = self.codes([], mode=mode, jumpcuts=cuts)
                    self.assertEqual("JUMP_CUT_UNCOVERED" in issues, expected)
                    if expected:
                        self.assertEqual((issues["JUMP_CUT_UNCOVERED"]["level"], issues["JUMP_CUT_UNCOVERED"]["severity"]), (1, "warning"))

    def test_mixed_all_quote_is_level_two_compatible_quality_issue(self):
        issue = self.codes([row(0)])["MIXED_NO_NARRATION"]
        self.assertEqual(set(issue), {"code", "severity", "message", "sentence_id", "level", "action"})
        self.assertEqual(issue["level"], 2)
        self.assertEqual(issue["severity"], "warning")
        self.assertIsNone(issue["sentence_id"])
        self.assertNotIn("MIXED_NO_NARRATION", self.codes([]))
        self.assertNotIn("MIXED_NO_NARRATION", self.codes([row(0), {"kind": "narration", "idx": 1}]))

    def test_warn_gate_does_not_demote_truth_errors_or_change_input(self):
        items = [row(7, source=None)]
        before = deepcopy(items)
        warn = evaluate_mode_checks(items, [], "mixed", {}, "warn")
        block = evaluate_mode_checks(items, [], "mixed", {}, "block")
        self.assertEqual(warn, block)
        self.assertEqual(warn[0]["severity"], "error")
        self.assertEqual(items, before)
        with self.assertRaises(ValueError):
            evaluate_mode_checks([], [], "mixed", {}, "invalid")

    def test_voiceover_has_no_quote_checks_original_has_no_pacing_checks(self):
        self.assertEqual(evaluate_mode_checks([row(0, source=None)], [], "voiceover", {"lower_third": True}), [])
        issues = evaluate_mode_checks([row(0)], [], "original", {"pacing": "fast"}, jumpcuts=[])
        self.assertEqual(issues, [])

    def test_original_invalid_range_reports_issue_instead_of_breaking_jump_checks(self):
        issues = evaluate_mode_checks([row(0), row(1, end=float("nan"))], [], "original", {})
        self.assertIn("QUOTE_INVALID_RANGE", {issue["code"] for issue in issues})


class IsolationTests(unittest.TestCase):
    def test_module_imports_only_stdlib_and_pydantic(self):
        tree = ast.parse(Path(pm.__file__).read_text(encoding="utf-8"))
        allowed = {"__future__", "hashlib", "json", "math", "re", "unicodedata", "bisect", "collections", "dataclasses", "decimal", "pathlib", "typing", "pydantic"}
        self.assertTrue(allowed - {"pydantic"} <= sys.stdlib_module_names)
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                self.assertTrue(all(alias.name.split(".")[0] in allowed for alias in node.names))
            elif isinstance(node, ast.ImportFrom):
                self.assertIn((node.module or "").split(".")[0], allowed)
                self.assertEqual(node.level, 0)

    def test_public_function_names_and_default_contracts(self):
        import inspect

        expected = {
            "parse_sentences": ["script", "mode", "kind_overrides"],
            "normalize_text": ["text"],
            "align_quotes": ["sentences", "uploads", "speakers"],
            "refine_cut": ["words", "start", "end", "duration", "silences"],
            "calculate_jumpcuts": ["rows", "cover"],
            "validate_quote_trim": ["source", "start", "end"],
            "evaluate_mode_checks": ["rows", "speakers", "mode", "preferences", "gate_mode", "jumpcuts"],
        }
        for name, parameters in expected.items():
            self.assertEqual(list(inspect.signature(getattr(pm, name)).parameters), parameters)
        default = inspect.signature(refine_cut).parameters["silences"].default
        self.assertEqual(default, [])
        refine_cut([Word(w="词", s=1, e=2)], 1, 2, 4)
        self.assertEqual(default, [])

    def test_fresh_import_and_functions_cannot_read_config_dotenv_data_or_use_network(self):
        original_import = builtins.__import__
        original_open = io.open
        denied = {"dotenv", "backend.config", "backend.main", "backend.providers", "requests", "httpx", "aiohttp"}
        opened: list[Path] = []
        rules_path = Path(pm.__file__).with_name("mode_rules.json").resolve()

        def guarded_import(name, *args, **kwargs):
            if any(name == prefix or name.startswith(prefix + ".") for prefix in denied):
                raise AssertionError("forbidden runtime import")
            return original_import(name, *args, **kwargs)

        def guarded_open(file, *args, **kwargs):
            path = Path(file).resolve()
            if path != rules_path:
                raise AssertionError("only adjacent shared rules may be opened")
            opened.append(path)
            return original_open(file, *args, **kwargs)

        spec = importlib.util.spec_from_file_location("_isolated_production_modes", pm.__file__)
        self.assertIsNotNone(spec)
        assert spec is not None and spec.loader is not None
        isolated = importlib.util.module_from_spec(spec)
        # Dataclasses need their owning module while annotations are postponed.
        with patch.dict(sys.modules, {spec.name: isolated}), \
             patch("builtins.__import__", side_effect=guarded_import), \
             patch("io.open", side_effect=guarded_open), \
             patch("builtins.open", side_effect=guarded_open), \
             patch.object(socket, "socket", side_effect=AssertionError("no network")), \
             patch.object(socket, "create_connection", side_effect=AssertionError("no network")):
            spec.loader.exec_module(isolated)
            sentences = isolated.parse_sentences("标题\n欢迎大家", "original")
            self.assertEqual(isolated.align_quotes(sentences, [upload(segment("欢迎大家"))])[0]["score"], 1.0)
            self.assertEqual(isolated.normalize_text("两百"), "200")
        self.assertEqual(opened, [rules_path])


if __name__ == "__main__":
    unittest.main()